
  SELECT D.name ,
         D.database_id ,
         D.create_date ,
         D.compatibility_level ,
         D.collation_name ,
         D.user_access_desc ,
         D.is_auto_close_on ,
         D.is_auto_shrink_on ,
         D.state_desc ,
         D.snapshot_isolation_state_desc ,
         D.is_read_committed_snapshot_on ,
         D.recovery_model_desc ,
         D.page_verify_option_desc ,
         D.is_auto_create_stats_on ,
         D.is_auto_update_stats_on ,
         D.is_ansi_nulls_on ,
         D.is_ansi_padding_on ,
         D.is_ansi_warnings_on ,
         D.is_arithabort_on ,
         D.is_concat_null_yields_null_on ,
         D.is_numeric_roundabort_on ,
         D.is_quoted_identifier_on ,
         D.is_recursive_triggers_on ,
         D.is_cursor_close_on_commit_on ,
         D.is_local_cursor_default ,
         D.is_fulltext_enabled ,
         D.is_trustworthy_on ,
         D.is_db_chaining_on ,
         D.is_parameterization_forced ,
         D.is_master_key_encrypted_by_server ,
         D.is_published ,
         D.is_subscribed ,
         D.is_merge_published ,
         D.is_distributor ,
         D.is_sync_with_backup ,
         D.service_broker_guid ,
         D.is_broker_enabled ,
         D.log_reuse_wait ,
         D.log_reuse_wait_desc ,
         D.is_date_correlation_on ,
         D.is_cdc_enabled ,
         D.is_encrypted ,
         D.is_honor_broker_priority_on ,
         D.containment ,
         D.containment_desc ,
         D.target_recovery_time_in_seconds FROM  sys.databases AS D

