 
DECLARE @TABELA TABLE (
	CODIGO	INT,
	CLIENTE	VARCHAR(25),
	PRODUTO VARCHAR(25)
);

-- Inserindo dados
INSERT INTO @TABELA VALUES(1,'JORGE','Piso');
INSERT INTO @TABELA VALUES(1,'JORGE','Porta');
INSERT INTO @TABELA VALUES(1,'JORGE','Torneira');

INSERT INTO @TABELA VALUES(2,'MARIA','Carriola');
INSERT INTO @TABELA VALUES(2,'MARIA','Torneira');



SELECT * FROM @TABELA AS T
-- Concatenando
SELECT  CODIGO,
		CLIENTE,
	COALESCE(
		(SELECT CAST(PRODUTO AS VARCHAR(10)) + ';' AS [text()]
		 FROM @TABELA AS O
		 WHERE O.CODIGO  = C.CODIGO
		 and   O.CLIENTE = C.CLIENTE
		 ORDER BY CODIGO
		 FOR XML PATH(''), TYPE).value('.[1]', 'VARCHAR(MAX)'), '') AS Produtos
FROM @TABELA AS C
GROUP BY CODIGO,CLIENTE


SELECT CODIGO,CLIENTE
     , STRING_AGG(PRODUTO, ',') WITHIN GROUP (ORDER BY PRODUTO) AS FieldBs
  FROM @TABELA
   GROUP BY CODIGO,CLIENTE
 ORDER BY CODIGO;
 
