
SELECT V.database_id,
       V.object_id,
       V.index_id,
	   V.avg_page_space_used_in_percent, -- Importante
	   V.avg_fragmentation_in_percent,
       V.partition_number,
       V.index_type_desc,
       V.alloc_unit_type_desc,
       V.index_depth,
       V.index_level,
       V.fragment_count,
       V.avg_fragment_size_in_pages,
       V.page_count,
       V.record_count,
       V.ghost_record_count,
       V.version_ghost_record_count,
       V.min_record_size_in_bytes,
       V.max_record_size_in_bytes,
       V.avg_record_size_in_bytes,
       V.forwarded_record_count,
       V.compressed_page_count,
       V.hobt_id,
       V.columnstore_delete_buffer_state,
       V.columnstore_delete_buffer_state_desc
  FROM sys.dm_db_index_physical_stats(DB_ID(N'WideWorldImporters'), 
  OBJECT_ID(N'Sales.OrderLines'), NULL, NULL, 'DETAILED') AS V;


  SELECT DDIOS.database_id,
         DDIOS.object_id,
         DDIOS.index_id,
         DDIOS.partition_number,
         DDIOS.hobt_id,
         DDIOS.leaf_insert_count,
         DDIOS.leaf_delete_count,
         DDIOS.leaf_update_count,
         DDIOS.leaf_ghost_count,
         DDIOS.nonleaf_insert_count,
         DDIOS.nonleaf_delete_count,
         DDIOS.nonleaf_update_count,
         DDIOS.leaf_allocation_count,
         DDIOS.nonleaf_allocation_count,
         DDIOS.leaf_page_merge_count,
         DDIOS.nonleaf_page_merge_count,
         DDIOS.range_scan_count,
         DDIOS.singleton_lookup_count,
         DDIOS.forwarded_fetch_count,
         DDIOS.lob_fetch_in_pages,
         DDIOS.lob_fetch_in_bytes,
         DDIOS.lob_orphan_create_count,
         DDIOS.lob_orphan_insert_count,
         DDIOS.row_overflow_fetch_in_pages,
         DDIOS.row_overflow_fetch_in_bytes,
         DDIOS.column_value_push_off_row_count,
         DDIOS.column_value_pull_in_row_count,
         DDIOS.row_lock_count,
         DDIOS.row_lock_wait_count,
         DDIOS.row_lock_wait_in_ms,
         DDIOS.page_lock_count,
         DDIOS.page_lock_wait_count,
         DDIOS.page_lock_wait_in_ms,
         DDIOS.index_lock_promotion_attempt_count,
         DDIOS.index_lock_promotion_count,
         DDIOS.page_latch_wait_count,
         DDIOS.page_latch_wait_in_ms,
         DDIOS.page_io_latch_wait_count,
         DDIOS.page_io_latch_wait_in_ms,
         DDIOS.tree_page_latch_wait_count,
         DDIOS.tree_page_latch_wait_in_ms,
         DDIOS.tree_page_io_latch_wait_count,
         DDIOS.tree_page_io_latch_wait_in_ms,
         DDIOS.page_compression_attempt_count,
         DDIOS.page_compression_success_count FROM sys.dm_db_index_operational_stats(db_id(),NULL,NULL,NULL) AS DDIOS