IF (OBJECT_ID('TEMPDB..#TmpLOGSPACE') IS NOT NULL)
    DROP TABLE #TmpLOGSPACE;


CREATE TABLE #TmpLOGSPACE (
    DatabaseName VARCHAR(100),
    LOGSIZE_MB DECIMAL(18, 9),
	LOGSIZE_GB AS (LOGSIZE_MB / 1024.0),
    LOGSPACE_USED DECIMAL(18, 9),
    LOGSTATUS DECIMAL(18, 9));

INSERT #TmpLOGSPACE (DatabaseName,
                     LOGSIZE_MB,
                     LOGSPACE_USED,
                     LOGSTATUS)
EXEC ('DBCC SQLPERF(LOGSPACE);');


SELECT * FROM #TmpLOGSPACE AS TL

--DBCC SQLPERF(waitstats)

