

SELECT * FROM [dbo].[Registro_Pessoas] AS [RP]


CREATE TABLE [dbo].[Registro_Pessoas](
	[IDPESSOA] INT  NULL,
	[IDLEGADO] INT NULL,
	[IDCONVERSAO]INT NULL,
	[IDSTATUSCONVERSAO] INT NULL,
	[DATACONVERSAO] [VARCHAR](10) NULL,
	[TIPOPESSOA] [VARCHAR](2) NULL,
	[NOME] [VARCHAR](300) NULL,
	[SEXO] [VARCHAR](1) NULL,
	[DATANASCIMENTO] [VARCHAR](10) NULL,
	[TIPOSANGUINEO] [VARCHAR](10) NULL,
	[ESTADOCIVIL] [VARCHAR](20) NULL,
	[NOMEPAI] [VARCHAR](300) NULL,
	[NOMEMAE] [VARCHAR](300) NULL,
	[ETNIA] [VARCHAR](200) NULL,
	[NOMECONJUGE] [VARCHAR](300) NULL,
	[NACIONALIDADE] [VARCHAR](200) NULL,
	[NATURALIDADE] [VARCHAR](200) NULL,
	[SIGLAUFNATURALIDADE] [VARCHAR](2) NULL,
	[SUBREGIAO] [VARCHAR](50) NULL,
	[DOADORORGAOS] [VARCHAR](1) NULL,
	[NATUREZAJURIDICA] [VARCHAR](300) NULL,
	[NOMEFANTASIA] [VARCHAR](300) NULL,
	[DATAFUNDACAO] [VARCHAR](10) NULL,
	[SIGLA] [VARCHAR](10) NULL,
	[ATIVIDADEECONOMICAPRINCIPAL] [VARCHAR](300) NULL,
	[ATIVIDADEECONOMICASECUNDARIA] [VARCHAR](300) NULL,
	[REGISTROJUNTACOMERCIAL] [VARCHAR](300) NULL,
	[NUMEROALTERACAOCONTRATUAL] [VARCHAR](100) NULL,
	[DATAREGISTROJUNTACOMERCIAL] [VARCHAR](10) NULL,
	[NOMECARTORIO] [VARCHAR](300) NULL,
	[NUMEROREGISTROCARTORIO] [VARCHAR](300) NULL,
	[DATACARTORIO] [VARCHAR](10) NULL,
	[FOLHAS] [VARCHAR](10) NULL,
	[PAGINAS] [VARCHAR](10) NULL,
	[AGRUPAR] [VARCHAR](1) NULL,
	[AGRUPARPRINCIPAL] [VARCHAR](1) NULL,
	[CPFCNPJ] [VARCHAR](20) NULL,
	[DATAATUALIZACAO] [VARCHAR](10) NULL,
	[NOMEUSUARIOATUALIZACAO] [VARCHAR](300) NULL,
	[NOMEUNIDADEATUALIZACAO] [VARCHAR](300) NULL,
	[DataCriacao] [VARCHAR](10) NULL,
	[NomeUsuarioCriacao] [VARCHAR](200) NULL,
	[NomeUnidadeCriacao] [VARCHAR](200) NULL,
	[StatusConversao] [VARCHAR](200) NULL,
	[RegiaoAdministrativa] [VARCHAR](200) NULL,
	[ReceberEmail] [VARCHAR](1) NULL,
	[ReceberRevista] [VARCHAR](1) NULL,
	[Observacao] [VARCHAR](500) NULL
) ON [PRIMARY]
GO




GO
DECLARE @path VARCHAR(MAX) = N'D:\Teste Bulk\';
DECLARE @arquivo VARCHAR(MAX) = N'REGISTRO_PESSOAS.txt';

DECLARE @pathArquivoErro VARCHAR(200) = CONCAT(@path, 'error.csv');

DECLARE @Target VARCHAR(MAX) = N'[dbo].[Registro_Pessoas]';

/*master : https://www.mssqltips.com/sqlservertip/4648/sql-server-bulk-insert-row-terminator-issues/ */

/*master :  https://www.sqlshack.com/how-to-import-flat-files-with-a-varying-number-of-columns-in-sql-server/ */





DECLARE @SQL_BULK1 VARCHAR(MAX);
SET @SQL_BULK1
    = 'BULK INSERT ' + @Target + ' FROM ''' + CONCAT(@path, @arquivo)
      + ''' WITH
        (
        MAXERRORS=0,
        FIELDTERMINATOR = '';'',
        ROWTERMINATOR = ''0x0a'',
		ERRORFILE =''' + @pathArquivoErro + '''
		
        
        )';

EXEC (@SQL_BULK1);


