SELECT SE.spid,
       SE.kpid,
       SE.blocked,
       SE.waittype,
       SE.waittime,
       SE.lastwaittype,
       [Bannco] = DB_NAME(SE.dbid),
       SE.uid,
       SE.cpu,
       SE.physical_io,
       SE.memusage,
       SE.login_time,
       SE.last_batch,
       SE.ecid,
       SE.open_tran,
       SE.status,
       SE.sid,
       SE.hostname,
       SE.program_name,
       SE.hostprocess,
       SE.cmd,
       SE.nt_domain,
       SE.nt_username,
       SE.net_address,
       SE.net_library,
       SE.loginame,
       SE.context_info,
       SE.sql_handle,
       SE.stmt_start,
       SE.stmt_end,
       SE.request_id,
	   s_est.dbid,
       s_est.objectid,
       s_est.number,
       s_est.encrypted,
       s_est.text
FROM sys.sysprocesses SE
    OUTER APPLY sys.dm_exec_sql_text(SE.sql_handle) AS [s_est]
WHERE SE.blocked > 1;