


CREATE FUNCTION [Helper].[ufnSomenteNumeros] 
	(@NUMERO VARCHAR(30))
RETURNS VARCHAR(30) 
AS
BEGIN
DECLARE @NOVO_NUMERO VARCHAR(30)
DECLARE @INDEX INT

SET @INDEX = 1
SET @NOVO_NUMERO = ''

WHILE @INDEX <= LEN(@NUMERO) 
 BEGIN
  IF SUBSTRING(@NUMERO,@INDEX,1 ) IN ('0','1','2','3','4','5','6','7','8','9')
    SET @NOVO_NUMERO = @NOVO_NUMERO +  SUBSTRING(@NUMERO,@INDEX,1 )
    SET @INDEX = @INDEX + 1
 END

RETURN @NOVO_NUMERO
END